trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: AzureCLI@2
    displayName: "Terraform Init, Plan and Apply"
    inputs:
      azureSubscription: "azure-aks-connection"
      scriptType: "bash"
      scriptLocation: "inlineScript"
      inlineScript: |
        cd terraform

        echo "Installing Terraform..."
        sudo apt-get update -y
        sudo apt-get install -y unzip

        TERRAFORM_VERSION="1.9.8"
        wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
        unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip
        sudo mv terraform /usr/local/bin/

        echo "Terraform version:"
        terraform version

        echo "Terraform Init..."
        terraform init

        echo "Terraform Validate..."
        terraform validate
                echo "Importing existing Resource Group..."
        terraform import azurerm_resource_group.aks_rg "/subscriptions/$(az account show --query id -o tsv)/resourceGroups/rg-aks-devops"

        echo "Terraform Plan..."
        terraform plan

        echo "Terraform Apply..."
        terraform apply -auto-approve
